[project]
name = "todoapp01"
version = "0.1.0"
description = "Add your description here"
readme = "backend/README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "sqlalchemy>=2.0.43",
    "uvicorn>=0.35.0",
]
